version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.09.0/24

volumes:
  postgres_data:
  user_data:

services:
  main:
    privileged: true
    image: "uxbox-devenv"
    hostname: 'uxbox-devenv-main'
    container_name: 'uxbox-devenv-main'
    command: "/home/uxbox/init.sh"
    stop_signal: SIGINT
    depends_on:
      - postgres
      - smtp
    volumes:
      - "user_data:/home/uxbox/local"
      - "${HOME}/.m2:/home/uxbox/.m2"
      - "${PWD}:/home/uxbox/uxbox"

    ports:
      - 3447:3447
      - 3448:3448
      - 3449:3449
      - 6060:6060
      - 9090:9090

    environment:
      - CLOJURE_OPTS=-J-XX:-OmitStackTraceInFastThrow
      - UXBOX_DATABASE_URI=postgresql://postgres/uxbox
      - UXBOX_DATABASE_USERNAME=uxbox
      - UXBOX_DATABASE_PASSWORD=uxbox

  smtp:
    container_name: 'uxbox-devenv-smtp'
    image: mwader/postfix-relay
    restart: always
    environment:
      - POSTFIX_myhostname=smtp.uxbox.io
      - OPENDKIM_DOMAINS=smtp.uxbox.io

  postgres:
    image: postgres:12
    command: postgres -c config_file=/etc/postgresql.conf
    hostname: 'uxbox-devenv-postgres'
    container_name: 'uxbox-devenv-postgres'
    restart: always
    stop_signal: SIGINT
    ports:
      - 5432:5432
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=uxbox
      - POSTGRES_USER=uxbox
      - POSTGRES_PASSWORD=uxbox
    volumes:
      - ./files/postgresql.conf:/etc/postgresql.conf
      - ./files/postgresql_init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
